/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNewRouteImport } from './routes/_authenticated/app.new'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/app.invoices'
import { Route as AuthenticatedAppFreelancersRouteImport } from './routes/_authenticated/app.freelancers'
import { Route as AuthenticatedAppFreelancerRouteImport } from './routes/_authenticated/app.freelancer'
import { Route as AuthenticatedAppEmployerRouteImport } from './routes/_authenticated/app.employer'
import { Route as AuthenticatedAppGigsIndexRouteImport } from './routes/_authenticated/app.gigs.index'
import { Route as AuthenticatedAppInvoiceIdRouteImport } from './routes/_authenticated/app.invoice.$id'
import { Route as AuthenticatedAppGigsNewRouteImport } from './routes/_authenticated/app.gigs.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppNewRoute = AuthenticatedAppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/app/messages',
    path: '/app/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/app/invoices',
    path: '/app/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFreelancersRoute =
  AuthenticatedAppFreelancersRouteImport.update({
    id: '/app/freelancers',
    path: '/app/freelancers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFreelancerRoute =
  AuthenticatedAppFreelancerRouteImport.update({
    id: '/app/freelancer',
    path: '/app/freelancer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmployerRoute =
  AuthenticatedAppEmployerRouteImport.update({
    id: '/app/employer',
    path: '/app/employer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppGigsIndexRoute =
  AuthenticatedAppGigsIndexRouteImport.update({
    id: '/app/gigs/',
    path: '/app/gigs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInvoiceIdRoute =
  AuthenticatedAppInvoiceIdRouteImport.update({
    id: '/app/invoice/$id',
    path: '/app/invoice/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppGigsNewRoute = AuthenticatedAppGigsNewRouteImport.update({
  id: '/app/gigs/new',
  path: '/app/gigs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/employer': typeof AuthenticatedAppEmployerRoute
  '/app/freelancer': typeof AuthenticatedAppFreelancerRoute
  '/app/freelancers': typeof AuthenticatedAppFreelancersRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/gigs/new': typeof AuthenticatedAppGigsNewRoute
  '/app/invoice/$id': typeof AuthenticatedAppInvoiceIdRoute
  '/app/gigs/': typeof AuthenticatedAppGigsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/employer': typeof AuthenticatedAppEmployerRoute
  '/app/freelancer': typeof AuthenticatedAppFreelancerRoute
  '/app/freelancers': typeof AuthenticatedAppFreelancersRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/messages': typeof AuthenticatedAppMessagesRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/gigs/new': typeof AuthenticatedAppGigsNewRoute
  '/app/invoice/$id': typeof AuthenticatedAppInvoiceIdRoute
  '/app/gigs': typeof AuthenticatedAppGigsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/employer': typeof AuthenticatedAppEmployerRoute
  '/_authenticated/app/freelancer': typeof AuthenticatedAppFreelancerRoute
  '/_authenticated/app/freelancers': typeof AuthenticatedAppFreelancersRoute
  '/_authenticated/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRoute
  '/_authenticated/app/new': typeof AuthenticatedAppNewRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/gigs/new': typeof AuthenticatedAppGigsNewRoute
  '/_authenticated/app/invoice/$id': typeof AuthenticatedAppInvoiceIdRoute
  '/_authenticated/app/gigs/': typeof AuthenticatedAppGigsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/employer'
    | '/app/freelancer'
    | '/app/freelancers'
    | '/app/invoices'
    | '/app/messages'
    | '/app/new'
    | '/app/profile'
    | '/app/'
    | '/app/gigs/new'
    | '/app/invoice/$id'
    | '/app/gigs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/employer'
    | '/app/freelancer'
    | '/app/freelancers'
    | '/app/invoices'
    | '/app/messages'
    | '/app/new'
    | '/app/profile'
    | '/app'
    | '/app/gigs/new'
    | '/app/invoice/$id'
    | '/app/gigs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/employer'
    | '/_authenticated/app/freelancer'
    | '/_authenticated/app/freelancers'
    | '/_authenticated/app/invoices'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/new'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/'
    | '/_authenticated/app/gigs/new'
    | '/_authenticated/app/invoice/$id'
    | '/_authenticated/app/gigs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/new': {
      id: '/_authenticated/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthenticatedAppNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/app/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/invoices': {
      id: '/_authenticated/app/invoices'
      path: '/app/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/freelancers': {
      id: '/_authenticated/app/freelancers'
      path: '/app/freelancers'
      fullPath: '/app/freelancers'
      preLoaderRoute: typeof AuthenticatedAppFreelancersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/freelancer': {
      id: '/_authenticated/app/freelancer'
      path: '/app/freelancer'
      fullPath: '/app/freelancer'
      preLoaderRoute: typeof AuthenticatedAppFreelancerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/employer': {
      id: '/_authenticated/app/employer'
      path: '/app/employer'
      fullPath: '/app/employer'
      preLoaderRoute: typeof AuthenticatedAppEmployerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/gigs/': {
      id: '/_authenticated/app/gigs/'
      path: '/app/gigs'
      fullPath: '/app/gigs/'
      preLoaderRoute: typeof AuthenticatedAppGigsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/invoice/$id': {
      id: '/_authenticated/app/invoice/$id'
      path: '/app/invoice/$id'
      fullPath: '/app/invoice/$id'
      preLoaderRoute: typeof AuthenticatedAppInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/gigs/new': {
      id: '/_authenticated/app/gigs/new'
      path: '/app/gigs/new'
      fullPath: '/app/gigs/new'
      preLoaderRoute: typeof AuthenticatedAppGigsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppEmployerRoute: typeof AuthenticatedAppEmployerRoute
  AuthenticatedAppFreelancerRoute: typeof AuthenticatedAppFreelancerRoute
  AuthenticatedAppFreelancersRoute: typeof AuthenticatedAppFreelancersRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRoute
  AuthenticatedAppNewRoute: typeof AuthenticatedAppNewRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppGigsNewRoute: typeof AuthenticatedAppGigsNewRoute
  AuthenticatedAppInvoiceIdRoute: typeof AuthenticatedAppInvoiceIdRoute
  AuthenticatedAppGigsIndexRoute: typeof AuthenticatedAppGigsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppEmployerRoute: AuthenticatedAppEmployerRoute,
  AuthenticatedAppFreelancerRoute: AuthenticatedAppFreelancerRoute,
  AuthenticatedAppFreelancersRoute: AuthenticatedAppFreelancersRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRoute,
  AuthenticatedAppNewRoute: AuthenticatedAppNewRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppGigsNewRoute: AuthenticatedAppGigsNewRoute,
  AuthenticatedAppInvoiceIdRoute: AuthenticatedAppInvoiceIdRoute,
  AuthenticatedAppGigsIndexRoute: AuthenticatedAppGigsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
